### ISSUE TITLE
Perfect in desktop, not working in mobile

### ISSUE THREAD

**Issue by ceruberu** [joe-bell/next-google-fonts#87] opened 2020-12-10 15:01 UTC
Is there some configurations I have to put for mobile devices?

**Comment by joe-bell** [comment] 2020-12-10 15:14
@ceruberu before I look into this, please can you complete the following:

1. [ ] Update this issue to follow the ["Bug Report" Template](https://github.com/joe-bell/next-google-fonts/issues/new?assignees=&labels=&template=bug_report.md&title=)
2. [ ] Provide a complete reproduction of your issue

**Comment by ceruberu** [comment] 2020-12-10 15:44
**Describe the bug**
A clear and concise description of what the bug is.

I followed your readme to implement google fonts,
and it works perfectly in web.
But when I open my website in my phones (chrome, samsung, safari),
the fonts do not work. 


**To Reproduce**
Steps to reproduce the behavior:
my _app.js
```
import { useEffect } from 'react'
import Head from 'next/head'
import { IntlProvider } from "react-intl"
import { useRouter } from "next/router"
import GoogleFonts from "next-google-fonts";


import * as locales from "../content/locale"
import * as gtag from '../lib/gtag'
import "../styles/globals.css"

function MyApp({ Component, pageProps }) {
  const router = useRouter()
  const { locale, defaultLocale, pathname, events } = router;

  const localeCopy = locales[locale]
  const messages = localeCopy[pathname]
  
  useEffect(() => {
    const handleRouteChange = (url) => {
      gtag.pageview(url)
    }
    router.events.on('routeChangeComplete', handleRouteChange)
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange)
    }
  }, [router.events])

  return (
    <IntlProvider
      locale={locale}
      defaultLocale={defaultLocale}
      messages={messages}
    >
      <Head>
        <GoogleFonts href="https://fonts.googleapis.com/css2?family=Prompt:wght@400;700&display=swap" />
        <meta key="viewport" name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <Component {...pageProps} />

    </IntlProvider>
  )
}

export default MyApp

```
my global.css

```
html,
body {
  height: 100%;
  padding: 0;
  margin: 0;
  font-family: Prompt, Enriqueta-Regular, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}
```


**Expected behavior**
A clear and concise description of what you expected to happen.

Work in both desktop and mobile

**Screenshots**
If applicable, add screenshots to help explain your problem.

My desktop (chrome)
<img width="426" alt="스크린샷 2020-12-10 오후 10 35 22" src="https://user-images.githubusercontent.com/21168032/101794039-08b22780-3b39-11eb-9449-a8c793661114.png">

My phone screenshot (chrome)
![43281](https://user-images.githubusercontent.com/21168032/101794062-0fd93580-3b39-11eb-9fa2-b513432ace73.jpg)


**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] samsung note10, iphone8
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari] chrome, samsung explorer, safari
- Version [e.g. 22]

**Comment by ceruberu** [comment] 2020-12-10 15:52
@joe-bell Is this good enough? Thanks

**Describe the bug**
A clear and concise description of what the bug is.

Not working in mobile

**To Reproduce**
Steps to reproduce the behavior:

my _app.js
```
import { useEffect } from 'react'
import Head from 'next/head'
import { IntlProvider } from "react-intl"
import { useRouter } from "next/router"
import GoogleFonts from "next-google-fonts";


import * as locales from "../content/locale"
import * as gtag from '../lib/gtag'
import "../styles/globals.css"

function MyApp({ Component, pageProps }) {
  const router = useRouter()
  const { locale, defaultLocale, pathname, events } = router;

  const localeCopy = locales[locale]
  const messages = localeCopy[pathname]
  
  useEffect(() => {
    const handleRouteChange = (url) => {
      gtag.pageview(url)
    }
    router.events.on('routeChangeComplete', handleRouteChange)
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange)
    }
  }, [router.events])

  return (
    <IntlProvider
      locale={locale}
      defaultLocale={defaultLocale}
      messages={messages}
    >
      <Head>
        <GoogleFonts href="https://fonts.googleapis.com/css2?family=Prompt:wght@400;700&display=swap" />
        <meta key="viewport" name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <Component {...pageProps} />

    </IntlProvider>
  )
}

export default MyApp

```



my global.scc
```
html,
body {
  height: 100%;
  padding: 0;
  margin: 0;
  font-family: Prompt, Enriqueta-Regular, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}

```

**Expected behavior**
A clear and concise description of what you expected to happen.
same font for both desktop and mobile

**Screenshots**
If applicable, add screenshots to help explain your problem.

my desktop 
<img width="426" alt="스크린샷 2020-12-10 오후 10 35 22" src="https://user-images.githubusercontent.com/21168032/101795193-3a77be00-3b3a-11eb-87d5-6e2cd21bb664.png">

my mobile
![43282](https://user-images.githubusercontent.com/21168032/101795164-32b81980-3b3a-11eb-8612-f407bdc3981b.jpg)


**Desktop (please complete the following information):**

- OS: [e.g. iOS] ios
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] samsung note10, iphone8
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari] chrome, samsungexplorer, safari
- Version [e.g. 22]

**Comment by joe-bell** [comment] 2020-12-11 07:24
Thanks @ceruberu!

In your example you're calling `GoogleFonts` inside `Head`, this is **not supported**; [the setup guide in the README](https://github.com/joe-bell/next-google-fonts#setup) should help to get you started (note the use of `Fragment`). To be honest though I'm not sure that's the issue here/not convinced this is to do with `next-google-fonts` 😕 

If you want me to look further I will still need a full reproduction (e.g. CodeSandbox)

**Comment by ceruberu** [comment] 2020-12-11 07:37
Oh I see that next-google-fonts are already nested inside next/head

```
 <IntlProvider
      locale={locale}
      defaultLocale={defaultLocale}
      messages={messages}
    >
      <GoogleFonts href="https://fonts.googleapis.com/css2?family=Prompt:wght@400;700&display=swap" />
      <Head>
        <meta key="viewport" name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <Component {...pageProps} />
```
putting it outside head made it working in mobile
So actually the browser was getting font from my mac itself, because I had it installed already.
Now just wondering if loading multiple next/heads is fine.

Thanks @joe-bell

**Comment by joe-bell** [comment] 2020-12-11 15:32
No worries! Rendering [multiple `next/head`s is totally fine](https://nextjs.org/docs/api-reference/next/head)

I'll close this as it looks like your issue has been resolved

**Closed as completed by joe-bell** 2020-12-11 15:32 UTC
Labels: please add a complete reproduction
